spring:
  application:
    name: e-commerce-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/e_commerce}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

app:
  jwt:
    public-key: ${JWT_PUBLIC_KEY_PATH:file:./src/main/resources/app.pub}
    private-key: ${JWT_PRIVATE_KEY_PATH:file:./src/main/resources/app.key}

  stripe:
    secret-key: ${STRIPE_API_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}

springdoc:
  swagger-ui:
    operations-sorter: method