spring:
  application:
    name: e-commerce-api

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

app:
  jwt:
    public-key: ${JWT_PUBLIC_KEY_PATH}
    private-key: ${JWT_PRIVATE_KEY_PATH}
    issuer: ${JWT_ISSUER:e-commerce-api}
    expiration: ${JWT_EXPIRATION:1h}

  stripe:
    secret-key: ${STRIPE_API_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}
    success-url: ${STRIPE_SUCCESS_URL}
    cancel-url: ${STRIPE_CANCEL_URL}

springdoc:
  swagger-ui:
    operations-sorter: method
