spring:
  application:
    name: e-commerce-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/e_commerce_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public:
            key: ${JWT_PUBLIC_KEY_PATH:classpath:app.pub}
          private:
            key: ${JWT_PRIVATE_KEY_PATH:classpath:app.key}

  stripe:
    api:
      key: ${STRIPE_API_KEY}
    public:
      key: ${STRIPE_PUBLIC_KEY}
    webhook:
      secret: ${STRIPE_WEBHOOK_SECRET}

springdoc:
  swagger-ui:
    operations-sorter: method